### ISSUE TITLE
[Feature] Exporting "My Library" as YML, and importing on another computer

### ISSUE THREAD

**Issue by Bananaman** [ajour/ajour#659]
This feature would massively help guilds and friends. It would also lead to more people using Ajour, for sure.

1. Have an "Export" button which generates a YML file, with a format that contains "addon name", "addon id (curse id or similar)", "source" (curse, wowinterface, github url, etc), "channel" (release, beta etc), and flavor (retail, tbc, etc).
2. Have an "Import" button, edit: Moved import ideas to a comment: https://github.com/ajour/ajour/issues/659#issuecomment-879358508

This would be a major feature to implement, but hey, a man can dream.

**Comment by casperstorm** [comment]
We have talked about this a few times before, and it would be a cool feature. What needs to be done is figure out what we need to do in order to be able to take a `addons.yml` and import it somewere else. @tarkah can maybe share some ideas here?

**Comment by casperstorm** [comment]
We should add two buttons, `Export` and `Import` and either make a new section in Settings, or place the to the left of the search bar in MyAddons. This we need to iterate a little bit, and see what works the best.

The `Export` button should open a window where the user can pick a location where they want to save the export file. The file should be a `.yml` file looking like:

```yml
---
retail:
- title: Simulationcraft
  source: curse
  source-id: 123
tbc:
- title: WeakAuras
  source: curse
  source-id: 321
```


Then the `Import` button should accept an exported file and check for collision and then install what is in the file.

**Comment by Bananaman** [comment]
@casperstorm That's good, and for Git URL imports, perhaps this format:

```yml
---
retail:
- title: Simulationcraft
  source: curse
  source-id: 123
tbc:
- title: WeakAuras
  source: curse
  source-id: 321
- title: Some Git Project
  source: git-github
  source-id: "https://github.com/SomeUser/SomeRepo"
  release-id: "20210629"
```

The release id would be the git tag/release name. Not sure if that would be necessary to include.
